{% set name = "bluesky-queueserver" %}
{% set version = "0.0.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bluesky-queueserver-{{ version }}.tar.gz
  sha256: 73883107a493c21915594b8cd4902375211ef620f1efcdd690bab4366d891172

build:
  number: 0
  noarch: python
  entry_points:
    - qserver = bluesky_queueserver.manager.qserver_cli:qserver
    - start-re-manager = bluesky_queueserver.manager.start_manager:start_manager
    - qserver-list-plans-devices = bluesky_queueserver.manager.profile_ops:gen_list_of_plans_and_devices_cli
    - qserver-zmq-keys = bluesky_queueserver.manager.qserver_cli:qserver_zmq_keys
    - qserver-console-monitor = bluesky_queueserver.manager.output_streaming:qserver_console_monitor_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - aioredis
    - bluesky
    - bluesky-kafka
    - databroker
    - event-model
    - json-rpc
    - jsonschema
    - matplotlib-base
    - msgpack-python >=1.0.0
    - msgpack-numpy
    - numpydoc
    - openpyxl
    - ophyd
    - pydantic
    - python >=3.8
    - python-multipart
    - pyyaml
    - pyzmq
    - requests
    - scikit-image

test:
  imports:
    - bluesky_queueserver
    - bluesky_queueserver.manager
  commands:
    - qserver --help
    - start-re-manager --help
    - qserver-list-plans-devices --help
    - qserver-zmq-keys --help
    - qserver-console-monitor --help
    - python -c "import os; import bluesky_queueserver; assert os.path.isdir(os.path.join(os.path.dirname(bluesky_queueserver.__file__), 'profile_collection_sim'))"
  requires:
    - pip

about:
  home: https://github.com/bluesky/bluesky-queueserver
  summary: Server for queueing plans
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/bluesky-queueserver
  dev_url: https://github.com/bluesky/bluesky-queueserver

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
